Import("env")


def source(file):
    return "#/src/" + file

env["source_files"] += [
    source("main.cpp")
]

# Compile Engine
SConscript("#/src/engine/SConscript", exports="env")

# Compile Game
SConscript("#/src/game/SConscript", exports="env")